# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4fba1d7f4489e78ce561ac0afe1489699a5409b0d6ee304bafb14b02f9194a2e288ecc220bc7050810f229494fe8468d36b71137ebf2b8bb7d421706497fa7f

test:
  secret_key_base: 50dc813f44761190241b18f70c1c18ed52a4bacc4a54e3eb5b496c8e667e12cf30a5f30c4edaf3b548c9ac67918db6cff44191c925d9b2eb33225087eb2bb7eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
